name: SpellCheck

on:
  pull_request:
    paths:
      - '.github/workflows/spellcheck.yml'
      - 'spellcheck.yaml'
      - '**/*.swift'
      - '**/*.md'
      - '**/*.strings'

jobs:
  SpellCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Check Spelling
      uses: UnicornGlobal/spellcheck-github-actions@master
